OPENAI_API_KEY = "your-openai-key"
OPENTRIPMAP_API_KEY = "your-opentripmap-key"
WEATHER_API_KEY = "your-weatherapi-key"
CURRENCY_API_KEY = "your-currency-key"
EVENTBRITE_API_KEY = "your-eventbrite-key"
AVIATION_STACK_API_KEY = "your-aviationstack-key"
TRANSITLAND_API_KEY = "your-transitland-key" 
